### ISSUE TITLE
Errors on load

### ISSUE THREAD

**Issue by EquipableMC** [Ekpoa/PoaSK#3]
[15:33:24 INFO]: [PoaSK] Enabling PoaSK v3.4.3
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! [Skript] Severe Error:
[15:33:24 ERROR]: #!#! class poa.poask.effects.EffBlockMarker generated an exception while loading
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Something went horribly wrong with Skript.
[15:33:24 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:33:24 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:33:24 ERROR]: #!#! Following plugins are probably related to this error in some way:
[15:33:24 ERROR]: #!#! PoaSK 
[15:33:24 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:33:24 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:33:24 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:33:24 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:33:24 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Stack trace:
[15:33:24 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredConstructor(java.lang.Class[])" because "poa.poask.effects.EffBlockMarker.markerClass" is null
[15:33:24 ERROR]: #!#!     at PoaSK (2).jar//poa.poask.effects.EffBlockMarker.<clinit>(EffBlockMarker.java:44)
[15:33:24 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[15:33:24 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[15:33:24 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.util.Utils.getClasses(Utils.java:201)
[15:33:24 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[15:33:24 ERROR]: #!#!     at PoaSK (2).jar//poa.poask.PoaSK.onEnable(PoaSK.java:40)
[15:33:24 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[15:33:24 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[15:33:24 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[15:33:24 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[15:33:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577)
[15:33:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[15:33:24 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Version Information:
[15:33:24 ERROR]: #!#!   Skript: 2.8.4 (latest)
[15:33:24 ERROR]: #!#!     Flavor: skriptlang-github
[15:33:24 ERROR]: #!#!     Date: 11:03:52.948789700
[15:33:24 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[15:33:24 ERROR]: #!#!   Minecraft: 1.19.4
[15:33:24 ERROR]: #!#!   Java: 17.0.10 (OpenJDK 64-Bit Server VM 17.0.10+7)
[15:33:24 ERROR]: #!#!   OS: Linux amd64 5.15.0-91-generic
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Server platform: Paper
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Current node: null
[15:33:24 ERROR]: #!#! Current item: null
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Thread: Server thread
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Language: english
[15:33:24 ERROR]: #!#! Link parse mode: DISABLED
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! End of Error.
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! [Skript] Severe Error:
[15:33:24 ERROR]: #!#! class poa.poask.effects.EffBrand generated an exception while loading
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Something went horribly wrong with Skript.
[15:33:24 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[15:33:24 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[15:33:24 ERROR]: #!#! Following plugins are probably related to this error in some way:
[15:33:24 ERROR]: #!#! PoaSK 
[15:33:24 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[15:33:24 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[15:33:24 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[15:33:24 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[15:33:24 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Stack trace:
[15:33:24 ERROR]: #!#! java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredConstructor(java.lang.Class[])" because "poa.poask.effects.EffBrand.brandPayloadClass" is null
[15:33:24 ERROR]: #!#!     at PoaSK (2).jar//poa.poask.effects.EffBrand.<clinit>(EffBrand.java:37)
[15:33:24 ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
[15:33:24 ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
[15:33:24 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.util.Utils.getClasses(Utils.java:201)
[15:33:24 ERROR]: #!#!     at Skript (7).jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
[15:33:24 ERROR]: #!#!     at PoaSK (2).jar//poa.poask.PoaSK.onEnable(PoaSK.java:40)
[15:33:24 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[15:33:24 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[15:33:24 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[15:33:24 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[15:33:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:577)
[15:33:24 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:488)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:345)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1120)
[15:33:24 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[15:33:24 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:840)
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Version Information:
[15:33:24 ERROR]: #!#!   Skript: 2.8.4 (latest)
[15:33:24 ERROR]: #!#!     Flavor: skriptlang-github
[15:33:24 ERROR]: #!#!     Date: 11:03:52.948789700
[15:33:24 ERROR]: #!#!   Bukkit: 1.19.4-R0.1-SNAPSHOT
[15:33:24 ERROR]: #!#!   Minecraft: 1.19.4
[15:33:24 ERROR]: #!#!   Java: 17.0.10 (OpenJDK 64-Bit Server VM 17.0.10+7)
[15:33:24 ERROR]: #!#!   OS: Linux amd64 5.15.0-91-generic
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Server platform: Paper
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Current node: null
[15:33:24 ERROR]: #!#! Current item: null
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Thread: Server thread
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! Language: english
[15:33:24 ERROR]: #!#! Link parse mode: DISABLED
[15:33:24 ERROR]: #!#! 
[15:33:24 ERROR]: #!#! End of Error.
[15:33:24 ERROR]: #!#!

**Comment by ThatPotatoDev** [comment]
is this even still a issue...
